# File: azure-pipelines\nightly-snapshot-releases\Nightly Common VSTS Release.yml
# Description: Assemble & publish Snapshot common release nightly to internal feed
name: $(date:yyyyMMdd)$(rev:.r)

trigger: none
pr: none

resources:
  pipelines:
  - pipeline: Nightly ADAL VSTS Release
    project: Engineering
    source: Nightly ADAL VSTS Release
    trigger:
      branches:
        include:
        - dev
  repositories:
  - repository: self
    type: git
    ref: dev

schedules:
- cron: 0 21 * * *
  branches:
    include:
    - dev
  always: true

jobs:
- template: ../templates/step/nighly-snapshot-releases/common.yml
  parameters:
    versionType: Snapshot