# File: azure-pipelines\maven-release\common.yml
# Description: Publish common to maven central (sonatype)
# https://search.maven.org/search?q=g:com.microsoft.identity%20AND%20a:common
# Variable: 'commonVersion' was defined in the Variables tab
name: $(date:yyyyMMdd)$(rev:.r)

trigger: none
pr: none

resources:
  repositories:
  - repository: self
    type: git
    ref: master

jobs:
- template: ../templates/steps/maven-release/maven-release-jobs.yml
  parameters:
    project: common
    projectVersion: ${{ variables.commonVersion }}
    gradleAssembleReleaseTask: common:clean common:build common:assembleRelease
    gradleGeneratePomFiletask: common:generatePomFileForDistReleasePublication
    aarSourceFolder: common\build\outputs\aar\
    jarSourceFolder: common\build\outputs\jar
    pomSourceFolder: common\build\publications\release\
    gpgAar: true
    gpgSourcesJar: true
    gpgJavadocJar: false
    gpgJar: false
