# File: credscan-policheck.yml
# https://docs.microsoft.com/en-us/azure/security/develop/yaml-configuration#credential-scanner-task
# https://microsoft.sharepoint.com/sites/globalreadiness/SitePages/PoliCheck.aspx

steps:
- task: securedevelopmentteam.vss-secure-development-tools.build-task-credscan.CredScan@3
  displayName: 'Run Credential Scanner'
  inputs:
    debugMode: false
- task: securedevelopmentteam.vss-secure-development-tools.build-task-policheck.PoliCheck@2
  displayName: 'Run PoliCheck'
  inputs:
    targetType: F
    result: PoliCheck.xml
    optionsFC: 1
    optionsXS: 1
    optionsSEV: '1|2'
    optionsPE: '1|2|3|4'
- task: PublishSecurityAnalysisLogs@2
  name: PublishSecurityAnalysisLogs15
  displayName: Publish Security Analysis Logs
- task: ComponentGovernanceComponentDetection@0
  displayName: Component Detection

