steps:
  - bash: |
      echo "Fetching labels from https://api.github.com/repos/$BUILD_REPOSITORY_ID/issues/$SYSTEM_PULLREQUEST_PULLREQUESTNUMBER/labels"
      temp=$(curl -s "https://api.github.com/repos/$BUILD_REPOSITORY_ID/issues/$SYSTEM_PULLREQUEST_PULLREQUESTNUMBER/labels" | jq '.[] | {name}')
      echo "##vso[task.setvariable variable=prLabels]$temp"
    condition: eq(variables['Build.Reason'], 'PullRequest')
    name: fetchPrCILabel
