# File: azure-pipelines\templates\steps\spotbugs.yml
# Description: Tasks to run Spotbugs (Assemble task must run first)
# https://github.com/AzureAD/android-complete/blob/master/plugins/buildsystem/docs/Spotbugs.md

parameters:
- name: project
- name: spotbugsCommand
  default: spotbugsLocalDebug
  values:
  - spotbugsLocalDebug
  - spotbugsDebug
- name: artifactName
  default: CodeAnalysisLogs

steps:
- task: Gradle@2
  displayName: 'Run Spotbugs'
  inputs:
    tasks: ${{ parameters.project }}:${{ parameters.spotbugsCommand }}
    publishJUnitResults: false
- task: PublishPipelineArtifact@1
  displayName: 'Publish Artifact: SpotBugs'
  inputs:
    targetPath: '$(Build.SourcesDirectory)\${{ parameters.project }}\build\reports\'
    ArtifactName: ${{ parameters.artifactName }}
  condition: failed()
