# File: azure-pipelines/continous-delivery/common.yml
# Description: Assemble & publish common release to internal feed
# Variable: 'ENV_VSTS_MVN_ANDROIDADAL_USERNAME' was defined in the Variables tab
# Variable: 'mvnAccessToken' was defined in the Variables tab
# Variable: 'customVersion' was defined in the Variables tab

name: 0.$(Date:yyyyMMdd)$(Rev:.r) # $(Build.BuildNumber) = name

trigger:
- dev
pr: none

variables:
  ${{ if eq(variables.customVersion, '') }}:
    versionNumber: $(Build.BuildNumber)
  ${{ else }}:
    versionNumber: ${{ variables.customVersion }}

pool:
  name: Hosted Windows 2019 with VS2019
jobs:
# common4j
- job: common4j_phase
  displayName: 'common4j: Build, Test and Publish'
  steps:
  - template: ../templates/steps/continous-delivery/assemble-publish-projversion.yml
    parameters:
      project: common4j
      prjVersion: $(versionNumber)
      publishFolder: common4j/build/output
# common
- job: common_phase
  displayName: 'common: Build, Test and Publish'
  dependsOn:
  - common4j_phase
  steps:
  - template: ../templates/steps/continous-delivery/assemble-publish-projversion.yml
    parameters:
      project: common
      prjVersion: $(versionNumber)
      publishFolder: common/build/outputs
# Key Vault
- job: keyvault_phase
  displayName: 'Key Vault: Build, Test and Publish'
  steps:
  - template: ../templates/steps/continous-delivery/assemble-publish-projversion.yml
    parameters:
      project: keyvault
      prjVersion: $(versionNumber)
      publishFolder: keyvault/build/libs
# Lab API
- job: labapi_phase
  displayName: 'Lab API: Build, Test and Publish'
  steps:
  - template: ../templates/steps/continous-delivery/assemble-publish-projversion.yml
    parameters:
      project: labapi
      prjVersion: $(versionNumber)
      publishFolder: labapi/build/libs
# Lab API Utilities
- job: labapiutilities_phase
  displayName: 'Lab API Utilities: Build, Test and Publish'
  dependsOn:
  - keyvault_phase
  - labapi_phase
  steps:
  - template: ../templates/steps/automation-cert.yml
    parameters:
      envVstsMvnAt: ENV_VSTS_MVN_ANDROIDCOMMON_ACCESSTOKEN
  - task: AzureKeyVault@2
    displayName: 'Get Key vault AndroidAutomationRunnerAppSecret'
    inputs:
      azureSubscription: 'MSIDLABS_ANDROID_KV'
      KeyVaultName: 'ADALTestInfo'
      SecretsFilter: 'AndroidAutomationRunnerAppSecret'
      RunAsPreJob: false
  - template: ../templates/steps/continous-delivery/assemble-publish-projversion.yml
    parameters:
      project: LabApiUtilities
      prjVersion: $(versionNumber)
      publishFolder: LabApiUtilities/build/libs
      testArguments: "-PlabSecret=$(AndroidAutomationRunnerAppSecret)"
# Test utils
- job: testutils_phase
  displayName: 'Test utils: Build, Test and Publish'
  dependsOn:
  - keyvault_phase
  - labapi_phase
  - common_phase
  steps:
  - template: ../templates/steps/continous-delivery/assemble-publish-projversion.yml
    parameters:
      project: testutils
      prjVersion: $(versionNumber)
      publishFolder: testutils/build/outputs
# UI Automation utilities
- job: uiautomationutilities_phase
  displayName: 'UI Automation utilities: Build, Test and Publish'
  dependsOn:
  - testutils_phase
  - common_phase
  steps:
  - template: ../templates/steps/continous-delivery/assemble-publish-projversion.yml
    parameters:
      project: uiautomationutilities
      prjVersion: $(versionNumber)
      publishFolder: uiautomationutilities/build/outputs
...
