# File: azure-pipelines\continous-delivery\common.yml
# Description: Assemble & publish common release to internal feed

name: $(Build.DefinitionName)_$(SourceBranchName)_$(versionNumber)

trigger:
- dev
pr: none

variables:
  ${{ if eq(variables.customVersion, '') }}:
    versionNumber: 0.$(Build.BuildId).$(Date:yyyyMMdd).$(Rev:.r)
  ${{ else }}:
    versionNumber: ${{ variables.customVersion }}

pool:
  name: Hosted Windows 2019 with VS2019
jobs:
# common4j
- job: common4j_phase
  displayName: 'common4j: Build, Test and Publish'
  steps:
  - template: ..\templates\steps\continous-delivery\assemble-publish-projversion.yml
    parameters:
      project: common4j
      prjVersion: $(versionNumber)
# common
- job: common_phase
  displayName: 'common: Build, Test and Publish'
  dependsOn:
  - common4j_phase
  steps:
  - template: ..\templates\steps\continous-delivery\assemble-publish-projversion.yml
    parameters:
      project: common
# Key Vault
- job: keyvault_phase
  displayName: 'Key Vault: Build, Test and Publish'
  steps:
  - template: ..\templates\steps\continous-delivery\assemble-publish-projversion.yml
    parameters:
      project: keyvault
# Lab API
- job: labapi_phase
  displayName: 'Lab API: Build, Test and Publish'
  steps:
  - template: ..\templates\steps\continous-delivery\assemble-publish-projversion.yml
    parameters:
      project: labapi
# Test utils
- job: testutils_phase
  displayName: 'Test utils: Build, Test and Publish'
  dependsOn:
  - keyvault_phase
  - labapi_phase
  - common_phase
  steps:
  - template: ..\templates\steps\continous-delivery\assemble-publish-projversion.yml
    parameters:
      project: testutils
# UI Automation utilities
- job: uiautomationutilities_phase
  displayName: 'UI Automation utilities: Build, Test and Publish'
  dependsOn:
  - testutils_phase
  - common_phase
  steps:
  - template: ..\templates\steps\continous-delivery\assemble-publish-projversion.yml
    parameters:
      project: uiautomationutilities
...
