# File: gpg-signing.yml

parameters:
- name: gpgSigning

steps:
- task: DownloadPipelineArtifact@2
  displayName: Download Pipeline Artifacts
  inputs:
    artifactName: build_outputs
- task: DownloadSecureFile@1
  name: private
  displayName: Download GPG private key
  inputs:
    secureFile: private.key
    retryCount: 5
- task: DownloadSecureFile@1
  name: public
  displayName: Download GPG public key
  inputs:
    secureFile: public.key
    retryCount: 5
- task: DownloadSecureFile@1
  name: passphrase
  displayName: Download GPG passphrase
  inputs:
    secureFile: passphrase.txt
    retryCount: 5
- task: Bash@3
  displayName: GPG Signing
  inputs:
    targetType: inline
    script: ${{ parameters.gpgSigning }}
