# File: azure-pipelines\pull-request-validation\build-consumers.yml
# Description: Test new common in ADAL / MSAL / Broker (assembleLocal and testLocalDebugUnitTest)
# Variable: 'ENV_VSTS_MVN_ANDROIDADACCOUNTS_USERNAME' was defined in the Variables tab
# Variable: 'mvnAccessToken' was defined in the Variables tab
# https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/use-personal-access-tokens-to-authenticate
# Variable: 'commonBranchName' common branch to be used when running the pipeline manually
name: $(date:yyyyMMdd)$(rev:.r)

trigger: none

parameters:
  - name: shouldSkipLongRunningTest
    displayName: Should skip long running test?
    type: boolean
    default: true

variables:
- name: shouldSkipLongRunningTest
  ${{ if parameters.shouldSkipLongRunningTest }}:
    value: "-PshouldSkipLongRunningTest"
  ${{ else }}:
    value: ""
- name: robolectricSdkVersion
  value: 28
- group: AndroidAuthClientVariables

resources:
  repositories:
  - repository: msal
    type: github
    name: AzureAD/microsoft-authentication-library-for-android
    ref: dev
    endpoint: ANDROID_GITHUB
  - repository: broker
    type: github
    name: AzureAD/ad-accounts-for-android
    ref: dev
    endpoint: ANDROID_GITHUB
  - repository: adal
    type: github
    name: AzureAD/azure-activedirectory-library-for-android
    ref: dev
    endpoint: ANDROID_GITHUB

stages:
- stage: validateConsumers
  displayName: 'Validate'
  pool:
    name: Hosted Windows 2019 with VS2019
  jobs:
  # setup
  - job: setupBranch
    displayName: Setup branch
    steps:
    - checkout: none
    - task: PowerShell@2
      name: setvarStep
      displayName: Set var branch
      inputs:
        targetType: inline
        script: |
          $branch = switch ( '$(Build.Reason)' )
          {
              PullRequest
              {
                '$(System.PullRequest.SourceBranch)'
              }
              Manual
              {
                '$(commonBranchName)'
              }
              default
              {
                ''
              }
          }
          Write-Output "$branch"
          echo "##vso[task.setvariable variable=commonBranch;isOutput=true]$branch"
    - powershell: |
        if ("$(setvarStep.commonBranch)" -eq "") {
          Write-Output "commonBranchName is not set using default common"
        }
        else{
          Write-Output "Using common branch $(setvarStep.commonBranch) in consumers"
        }
      name: echovar
      displayName: Echo branch name
  # Check PR Label
  - job: checkLabel
    displayName: Check for PR Label
    dependsOn: setupBranch
    steps:
    - bash: |
        echo "Looking for label at https://api.github.com/repos/$BUILD_REPOSITORY_ID/issues/$SYSTEM_PULLREQUEST_PULLREQUESTNUMBER/labels"
        if curl -s "https://api.github.com/repos/$BUILD_REPOSITORY_ID/issues/$SYSTEM_PULLREQUEST_PULLREQUESTNUMBER/labels" | grep '"name": "Consumer-Validation-Optional"'
        then
          echo "##vso[task.setvariable variable=validationOptional;isOutput=true]true"
          echo "Skip-Consumers-Check label found, skip validation"
        fi
      condition: eq(variables['Build.Reason'], 'PullRequest')
      name: checkPrCILabel
  # msal
  - job: msalValidation
    displayName: MSAL
    dependsOn:
      - setupBranch
      - checkLabel
    variables:
      commonBranch: $[ dependencies.setupBranch.outputs['setvarStep.commonBranch'] ]  # map in the variable
      validationOptional: $[ dependencies.checkLabel.outputs['checkPrCILabel.validationOptional'] ]
    continueOnError: ${{ eq(variables['validationOptional'], 'true') }}
    steps:
    - template: ../templates/steps/automation-cert.yml
    - checkout: msal
      displayName: Checkout msal repository
      clean: true
      submodules: recursive
      persistCredentials: True
    - task: CmdLine@2
      displayName: Checkout common submodule $(commonBranch)
      inputs:
        script: |
          git fetch
          git checkout $(commonBranch)
          git pull
          git status
          git rev-parse HEAD
        workingDirectory: $(Agent.BuildDirectory)/s/common
    - task: Gradle@2
      displayName: Assemble msal
      continueOnError: $(validationOptional)
      inputs:
        tasks: clean msal:assembleLocal
    - task: Gradle@2
      displayName: Run msal Unit tests
      continueOnError: $(validationOptional)
      inputs:
        tasks: msal:testLocalDebugUnitTest -Plabtest -ProbolectricSdkVersion=${{variables.robolectricSdkVersion}}
  # broker
  - job: brokerValidation
    displayName: Broker
    cancelTimeoutInMinutes: 1
    timeoutInMinutes: 120
    dependsOn:
      - setupBranch
      - checkLabel
    variables:
      commonBranch: $[ dependencies.setupBranch.outputs['setvarStep.commonBranch'] ]  # map in the variable
      validationOptional: $[ dependencies.checkLabel.outputs['checkPrCILabel.validationOptional'] ]
    pool:
      name: 1ES-AndroidPool-EOC-Test
    steps:
    - template: ../templates/steps/automation-cert.yml
    - checkout: broker
      displayName: Checkout broker repository
      clean: true
      submodules: recursive
      persistCredentials: True
    - task: CmdLine@2
      displayName: Checkout common submodule $(commonBranch)
      inputs:
        script: |
          git fetch
          git checkout $(commonBranch)
          git pull
          git status
          git rev-parse HEAD
        workingDirectory: $(Agent.BuildDirectory)/s/common
    - task: Gradle@2
      displayName: Assemble broker
      continueOnError: $(validationOptional)
      inputs:
        tasks: AADAuthenticator:clean AADAuthenticator:assembleLocal --build-cache --info
        publishJUnitResults: false
        jdkArchitecture: x86
        sqAnalysisBreakBuildIfQualityGateFailed: false
    - task: Gradle@2
      displayName: Run broker Unit tests
      continueOnError: $(validationOptional)
      inputs:
        tasks: AADAuthenticator:localDebugAADAuthenticatorUnitTestCoverageReport --build-cache --info -Plabtest -ProbolectricSdkVersion=${{variables.robolectricSdkVersion}} -PpowerLiftApiKey=$(powerliftApiKey) -PcodeCoverageEnabled=true ${{variables.shouldSkipLongRunningTest}}
  # Linux broker
  - job: linuxBrokerValidation
    displayName: Linux Broker
    dependsOn:
      - setupBranch
      - checkLabel
    variables:
      commonBranch: $[ dependencies.setupBranch.outputs['setvarStep.commonBranch'] ]  # map in the variable
      validationOptional: $[ dependencies.checkLabel.outputs['checkPrCILabel.validationOptional'] ]
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - checkout: broker
        displayName: Checkout broker repository
        clean: true
        submodules: recursive
        persistCredentials: True
      - task: CmdLine@1
        displayName: Set MVN Access Token in Environment
        inputs:
          filename: echo
          arguments: '##vso[task.setvariable variable=ENV_VSTS_MVN_ANDROIDADACCOUNTS_ACCESSTOKEN]$(System.AccessToken)'
      - task: CmdLine@1
        displayName: Set Office MVN Access Token in Environment
        inputs:
          filename: echo
          arguments: '##vso[task.setvariable variable=ENV_VSTS_MVN_OFFICE_ACCESSTOKEN]$(System.AccessToken)'
      - task: Gradle@1
        name: Gradle1
        displayName: Assemble Linux Broker
        continueOnError: $(validationOptional)
        inputs:
          cwd: $(Build.SourcesDirectory)/broker-java-root
          tasks: LinuxBroker:clean LinuxBroker:assemble --build-cache --info
          publishJUnitResults: false
          jdkArchitecture: x86
          sqAnalysisBreakBuildIfQualityGateFailed: false
      - task: Bash@3
        retryCountOnTaskFailure: 3
        continueOnError: $(validationOptional)
        displayName: Execute tests
        inputs:
          workingDirectory: $(Build.SourcesDirectory)/broker-java-root
          targetType: 'inline'
          script: |
            sudo apt-get install -y dbus-x11
            sudo apt-get install -y dos2unix
            dos2unix gradlew
            chmod +x gradlew
            export DISPLAY=:0.0
            eval $(dbus-launch --sh-syntax)
            sudo apt install gnome-keyring
            /usr/bin/gnome-keyring-daemon --start --components=secrets
            ./gradlew LinuxBroker:linuxBrokerUnitTestCoverageReport -Plabtest -ProbolectricSdkVersion=${{variables.robolectricSdkVersion}} -PcodeCoverageEnabled=true -Psystemd_mode_enabled=false
      - task: PublishTestResults@2
        condition: succeededOrFailed()
        inputs:
          testResultsFormat: 'JUnit'
          testResultsFiles: '**/TEST-*.xml'
          searchFolder: 'LinuxBroker'
  # adal
  - job: adalValidation
    displayName: ADAL
    dependsOn:
      - setupBranch
      - checkLabel
    variables:
      commonBranch: $[ dependencies.setupBranch.outputs['setvarStep.commonBranch'] ]  # map in the variable
      validationOptional: $[ dependencies.checkLabel.outputs['checkPrCILabel.validationOptional'] ]
    steps:
    - checkout: adal
      displayName: Checkout adal repository
      clean: true
      submodules: recursive
      persistCredentials: True
    - task: CmdLine@2
      displayName: Checkout common submodule $(commonBranch)
      inputs:
        script: |
          git fetch
          git checkout $(commonBranch)
          git pull
          git status
          git rev-parse HEAD
        workingDirectory: $(Agent.BuildDirectory)/s/common
    - task: Gradle@2
      displayName: Assemble adal
      continueOnError: $(validationOptional)
      inputs:
        tasks: clean adal:assembleLocal
    - task: Gradle@2
      displayName: Run adal Unit tests
      continueOnError: $(validationOptional)
      inputs:
        tasks: adal:testLocalDebugUnitTest -Plabtest -ProbolectricSdkVersion=${{variables.robolectricSdkVersion}}
