# File: azure-pipelines\pull-request-validation\common.yml
# Description: Assemble and run unit test
name: $(date:yyyyMMdd)$(rev:.r)

trigger:
  branches:
    include:
    - dev
    - master
    - release/*
  batch: True

resources:
  repositories:
  - repository: self
    type: git
    ref: dev

jobs:
- job: build_test
  displayName: Build & Test
  cancelTimeoutInMinutes: 1
  pool:
    name: Hosted Windows 2019 with VS2019
  steps:
  - checkout: self
    clean: true
    submodules: recursive
    persistCredentials: True
  - template: ../templates/steps/automation-cert.yml
  - task: CmdLine@1
    displayName: Set Office MVN Access Token in Environment
    inputs:
      filename: echo
      arguments: '##vso[task.setvariable variable=ENV_VSTS_MVN_ANDROIDCOMMON_ACCESSTOKEN]$(System.AccessToken)'
  - task: Gradle@3
    name: Gradle3   
    displayName: Assemble Local
    inputs:
      javaHomeSelection: JDKVersion
      jdkVersionOption: "1.11"
      tasks: clean common:assembleLocal
      publishJUnitResults: false
      jdkArchitecture: x64
      sqAnalysisEnabled: false
   - task: Gradle@1
     displayName: Lint Local debug
     inputs:
       tasks: clean common:lintLocalDebug
  - template: ../templates/steps/spotbugs.yml
    parameters:
      project: common
  - task: Gradle@2
    displayName: Run Unit tests
    inputs:
      javaHomeSelection: JDKVersion
      jdkVersionOption: "1.11"
      tasks: common:testLocalDebugUnitTest
...
