# 'Allow scripts to access the OAuth token' was selected in pipeline.  Add the following YAML to any steps requiring access:
#       env:
#           MY_ACCESS_TOKEN: $(System.AccessToken)
# Variable 'android:serverUrl' was defined in the Variables tab
# Variable 'ENV_VSTS_MVN_ANDROIDADACCOUNTS_USERNAME' was defined in the Variables tab
# Variable 'mvnAccessToken' was defined in the Variables tab
# Variable 'test_repo_branch' was defined in the Variables tab
# Variable 'test_repo_dir' was defined in the Variables tab
trigger:
  branches:
    include:
    - dev
    - master
  batch: True
name: $(date:yyyyMMdd)$(rev:.r)
resources:
  repositories:
  - repository: self
    type: git
    ref: dev
jobs:
- job: Phase_1
  displayName: Phase 1
  cancelTimeoutInMinutes: 1
  pool:
    name: Hosted Windows 2019 with VS2019
  steps:
  - checkout: self
    clean: true
    submodules: recursive
    persistCredentials: True
  - template: ../templates/steps/credscan-policheck.yml
    parameters:
      policheck-cmdlineargs-dir: adal
  - task: CmdLine@1
    displayName: Set MVN Access Token in Environment
    inputs:
      filename: echo
      arguments: '##vso[task.setvariable variable=ENV_VSTS_MVN_ANDROIDADACCOUNTS_ACCESSTOKEN]$(mvnAccessToken)'
  - task: AzureKeyVault@1
    displayName: 'Azure Key Vault: Download Cert for Automation'
    inputs:
      ConnectedServiceName: 52f0b8f0-fbe7-4c1b-8169-25886eb6bab4
      KeyVaultName: ADALTestInfo
      SecretsFilter: AndroidAutomationRunner
  - task: PowerShell@2
    displayName: Install Automation Cert
    inputs:
      targetType: inline
      script: >
        $kvSecretBytes = [System.Convert]::FromBase64String('$(AndroidAutomationRunner)')

        $certCollection = New-Object System.Security.Cryptography.X509Certificates.X509Certificate2Collection

        $certCollection.Import($kvSecretBytes, $null, [System.Security.Cryptography.X509Certificates.X509KeyStorageFlags]::Exportable)


        $protectedCertificateBytes = $certCollection.Export([System.Security.Cryptography.X509Certificates.X509ContentType]::Pkcs12)

        $pfxPath = '$(Build.SourcesDirectory)' + "\TestCert.pfx"

        [System.IO.File]::WriteAllBytes($pfxPath, $protectedCertificateBytes)


        Import-PfxCertificate -FilePath $pfxPath -CertStoreLocation Cert:\CurrentUser\My
  - task: Gradle@1
    name: Gradle1
    displayName: Assemble Release
    inputs:
      tasks: clean common:assemble
      publishJUnitResults: false
      jdkArchitecture: x86
      sqAnalysisBreakBuildIfQualityGateFailed: false
  - task: Gradle@2
    displayName: Run Unit tests
    inputs:
      tasks: common:testDebugUnitTest
  - task: ComponentGovernanceComponentDetection@0
    displayName: Component Detection
...
