# File: azure-pipelines\pull-request-validation\common.yml
# Description: Assemble and run unit test
name: $(date:yyyyMMdd)$(rev:.r)

trigger:
  branches:
    include:
    - dev
    - master
    - release/*
  batch: True

variables:
- name: robolectricSdkVersion
  value: 29

resources:
  repositories:
  - repository: self
    type: git
    ref: dev

jobs:
- job: build_test
  displayName: Build & Test
  cancelTimeoutInMinutes: 1
  pool:
    name: Hosted Windows 2019 with VS2019
  steps:
  - checkout: self
    clean: true
    submodules: recursive
    persistCredentials: True
  - template: ../templates/steps/automation-cert.yml
  - task: Gradle@1
    name: Gradle1
    displayName: Assemble Release
    inputs:
      tasks: clean common:assembleLocal
      publishJUnitResults: false
      jdkArchitecture: x86
      sqAnalysisBreakBuildIfQualityGateFailed: false
  - template: ../templates/steps/spotbugs.yml
    parameters:
      project: common
  - task: Gradle@2
    displayName: Run Unit tests
    inputs:
      tasks: common:testLocalDebugUnitTest
  - task: Gradle@3
    displayName: Run common code coverage
    inputs:
      tasks: common:localDebugCommonUnitTestCoverageReport -Plabtest -ProbolectricSdkVersion=${{variables.robolectricSdkVersion}}
  - task: PublishCodeCoverageResults@1
    displayName: 'Publish code coverage report'
    inputs:
      summaryFileLocation: '$(Build.SourcesDirectory)\common\build\reports\jacoco\localDebugCommonUnitTestCoverageReport\localDebugCommonUnitTestCoverageReport.xml'
      reportDirectory: '$(Build.SourcesDirectory)\common\build\reports\jacoco\localDebugCommonUnitTestCoverageReport\html'
