# File: azure-pipelines\pull-request-validation\credscan.yml
# Description: Run Credscan and PoliCheck
name: $(date:yyyyMMdd)$(rev:.r)

trigger:
  branches:
    include:
    - dev
    - master
    - release/*
  batch: True

jobs:
- template: ../templates/steps/credscan-policheck.yml
...
