# File: azure-pipelines\pull-request-validation\lab-utilities.yml
# Description: Run test in LabApiUtilities
name: $(date:yyyyMMdd)$(rev:.r)

trigger: none

resources:
  repositories:
    - repository: self
      type: git
      ref: dev

pool:
  name: Hosted Windows 2019 with VS2019

jobs:
  - job: Phase_1
    displayName: Phase 1
    steps:
      - checkout: self
        clean: true
        submodules: recursive
        persistCredentials: True
      - template: ../templates/steps/credscan-policheck.yml
        parameters:
          policheckCmdLineArgsDir: common
      - template: ../templates/steps/automation-cert.yml
      - task: Gradle@1
        name: Gradle1
        displayName: Assembles the outputs of this project.
        inputs:
          tasks: LabApiUtilities:clean LabApiUtilties:assemble
      - task: Gradle@2
        displayName: Run the unit tests.
        inputs:
          tasks: LabApiUtilities:test -Psugar=true
      - task: ComponentGovernanceComponentDetection@0
        displayName: Component Detection
...
