# File: azure-pipelines\pull-request-validation\msal.yml
# Description:
name: $(date:yyyyMMdd)$(rev:.r)

trigger: none

variables:
- name: robolectricSdkVersion
  value: 28

resources:
  repositories:
  - repository: msal
    type: github
    name: AzureAD/microsoft-authentication-library-for-android
    ref: dev
    endpoint: ANDROID_GITHUB

stages:
- stage: validateConsumers
  displayName: Validate Consumers
  pool:
    name: Hosted Windows 2019 with VS2019
  jobs:
  - job: init
    displayName: setup
    steps:
      - template: ../templates/steps/automation-cert.yml
  - job: msalValidation
    displayName: msal validation
    cancelTimeoutInMinutes: 1
    steps:
    - checkout: msal
      clean: true
      submodules: recursive
      persistCredentials: True
    - task: CmdLine@2
      displayName: Checkout common submodule ($(System.PullRequest.SourceBranch))
      inputs:
        script: |
          git fetch
          git status
          git rev-parse HEAD
        workingDirectory: $(Agent.BuildDirectory)/s/microsoft-authentication-library-for-android/common
    - task: Gradle@2
      displayName: Assemble msal
      inputs:
        gradleWrapperFile: $(Agent.BuildDirectory)/s/microsoft-authentication-library-for-android/gradlew.bat
        cwd: $(Agent.BuildDirectory)/s/microsoft-authentication-library-for-android
        tasks: clean msal:assembleLocal
    - task: Gradle@2
      displayName: Run msal Unit tests
      inputs:
        gradleWrapperFile: $(Agent.BuildDirectory)/s/microsoft-authentication-library-for-android/gradlew.bat
        cwd: $(Agent.BuildDirectory)/s/microsoft-authentication-library-for-android
        tasks: msal:testLocalDebugUnitTest -Plabtest -ProbolectricSdkVersion=${{variables.robolectricSdkVersion}}
