# File: azure-pipelines\pull-request-validation\msal.yml
# Description: Test new common in ADAL / MSAL / Broker (assembleLocal and testLocalDebugUnitTest)
# Variable: 'ENV_VSTS_MVN_ANDROIDADACCOUNTS_USERNAME' was defined in the Variables tab
# Variable: 'mvnAccessToken' was defined in the Variables tab
# https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/use-personal-access-tokens-to-authenticate
# Variable: 'commonBranchName' was defined in the Variables tab
name: $(date:yyyyMMdd)$(rev:.r)

trigger: none

variables:
- name: robolectricSdkVersion
  value: 28

resources:
  repositories:
  - repository: msal
    type: github
    name: AzureAD/microsoft-authentication-library-for-android
    ref: dev
    endpoint: ANDROID_GITHUB
  - repository: broker
    type: github
    name: AzureAD/ad-accounts-for-android
    ref: dev
    endpoint: ANDROID_GITHUB
  - repository: adal
    type: github
    name: AzureAD/azure-activedirectory-library-for-android
    ref: dev
    endpoint: ANDROID_GITHUB

stages:
- stage: validateConsumers
  displayName: Validate Consumers
  pool:
    name: Hosted Windows 2019 with VS2019
  jobs:
  # setup
  - job: setupBranch
    displayName: setup branch
    steps:
    - task: PowerShell@2
      displayName: Define branch
      inputs:
        targetType: inline
        script: |

          $branch = switch ( '$(Build.Reason)' )
          {
              PullRequest
              {
                '$(System.PullRequest.SourceBranch)'
              }
              Manual
              {
                '$(commonBranchName)'
              }
              default
              {
                ''
              }
          }
          Write-Host "##vso[task.setvariable variable=commonBranch;]$branch"
          Write-Host "$(variables.commonBranch)"