# File: azure-pipelines\pull-request-validation\msal.yml
# Description:
name: $(date:yyyyMMdd)$(rev:.r)

trigger: none

variables:
- name: robolectricSdkVersion
  value: 28

resources:
  repositories:
  - repository: msal
    type: github
    name: AzureAD/microsoft-authentication-library-for-android
    ref: dev
    endpoint: ANDROID_GITHUB
  - repository: broker
    type: github
    name: AzureAD/ad-accounts-for-android
    ref: dev
    endpoint: ANDROID_GITHUB

stages:
- stage: validateConsumers
  displayName: Validate Consumers
  pool:
    name: Hosted Windows 2019 with VS2019
  jobs:
  - job: init
    displayName: setup
    steps:
      - template: ../templates/steps/automation-cert.yml
  # msal
  - job: msalValidation
    displayName: msal validation
    cancelTimeoutInMinutes: 1
    steps:
    - checkout: msal
      displayName: Checkout msal repository
      clean: true
      submodules: recursive
      persistCredentials: True
    - task: CmdLine@2
      displayName: Checkout common submodule $(System.PullRequest.SourceBranch)
      inputs:
        script: |
          git fetch
          git status
          git rev-parse HEAD
        workingDirectory: $(Agent.BuildDirectory)/s/common
    - task: Gradle@2
      displayName: Assemble msal
      inputs:
        tasks: clean msal:assembleLocal
    - task: Gradle@2
      displayName: Run msal Unit tests
      inputs:
        tasks: msal:testLocalDebugUnitTest -Plabtest -ProbolectricSdkVersion=${{variables.robolectricSdkVersion}}
  # broker
  - job: brokerValidation
    displayName: broker validation
    cancelTimeoutInMinutes: 1
    steps:
    - checkout: broker
      displayName: Checkout broker repository
      clean: true
      submodules: recursive
      persistCredentials: True
    - task: CmdLine@2
      displayName: Checkout common submodule $(System.PullRequest.SourceBranch)
      inputs:
        script: |
          git fetch
          git status
          git rev-parse HEAD
        workingDirectory: $(Agent.BuildDirectory)/s/common
    - task: PowerShell@2
      displayName: Install Flatbuffers Compiler
      enabled: False
      inputs:
        targetType: inline
        script: >-
          Write-Output "Downloading flatbuffers"

          $downloadLink = "https://github.com/google/flatbuffers/releases/download/v1.12.0/flatc_windows.zip"

          Write-Output "Using download link: $downloadLink"

          $dest = "$env:Temp\FlatBufferInstaller.zip"

          (New-Object Net.WebClient).DownloadFile($downloadLink, $dest)

          Write-Output "Extracting flatbuffers archive on machine...."

          Expand-Archive -Path $dest -DestinationPath .\flatc-extracted

          Write-Output "Finished extracting flatbuffers archive on machine...."

          Write-Output "Run flatc"

          .\flatc-extracted\flatc

          echo '##vso[task.setvariable variable=path]$(PATH):$(CWD)\flatc-extracted\'

          flatc
    - task: Gradle@2
      displayName: Assemble broker
      inputs:
        tasks: clean AADAuthenticator:assembleLocal
    - task: Gradle@2
      displayName: Run broker Unit tests
      inputs:
        tasks: AADAuthenticator:testLocalDebugUnitTest -Plabtest -ProbolectricSdkVersion=${{variables.robolectricSdkVersion}}
