name: Code coverage

on:
  pull_request:

env:
  ROBOLECTRIC_SDK_VERSION: 28

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Run Coverage
        run: ./gradlew common:localDebugCommonUnitTestCoverageReport -ProbolectricSdkVersion=$ROBOLECTRIC_SDK_VERSION -PcodeCoverageEnabled=true

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          file: ${{ github.workspace }}/common/build/reports/jacoco/localDebugCommonUnitTestCoverageReport/localDebugCommonUnitTestCoverageReport.xml
