# This is a workflow to run the deploy snapshot pipeline in Azure DevOps
name: dev_updated

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the dev branch
on:
  push:
    branches: [ pedroro/dev ]
    paths-ignore:
    - 'common/versioning/version.properties'
    - 'common4j/versioning/version.properties'

jobs:
  # Merge to continuous-delivery branch
  mergeToContinuousDelivery:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: everlytic/branch-merge@1.1.2
        with:
          github_token: ${{ github.token }}
          source_ref: ${{ github.ref }}
          target_branch: 'pedroro/continuous-delivery'
          commit_message_template: '[Automated] Merged {source_ref} into target {target_branch}'
  incrementLatestPatch:
    needs: mergeToContinuousDelivery
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.ACTION_PAT }}
        ref: pedroro/continuous-delivery
    - uses: actions/setup-java@v1
      with:
        java-version: 8
    - uses: eskatos/gradle-command-action@v1
      with:
        arguments: common:incrementLatestVersion common4j:incrementLatestVersion
    - run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add .
        git commit -m "Increment latest patch version"
        git push
  build:
    # Make this workflow sequential by indicating what this job needs in order to run
    needs: incrementLatestPatch
    runs-on: ubuntu-latest
    steps:
      - name: Azure Pipelines Action
        uses: Azure/pipelines@v1
        with:
          # Fullyqualified URL to the Azure DevOps organization along with project name(eg, https://dev.azure.com/organization/project-name or https://server.example.com:8080/tfs/DefaultCollection/project-name)
          azure-devops-project-url: 'https://dev.azure.com/IdentityDivision/IDDP'
          # Name of the Azure Pipline to be triggered
          azure-pipeline-name: 'Latest Common VSTS Release'
          # Paste personal access token of the user as value of secret variable:AZURE_DEVOPS_TOKEN
          azure-devops-token: '${{ secrets.IDDP_PIPELINE }}'
  